#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=~/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xset -b
xset r rate 240 80
xsetroot -cursor_name left_ptr
#setxkbmap -option ctrl:swapcaps
sh ~/.fehbg
exec bspwm

#xmodmap -e "keycode 104 = Return"
#xmodmap -e "keycode 90 = Tab"
