#!/bin/sh

if [ ! -f "$1" ] ; then
    echo "Please, input a string!"
fi

pkill -9 feh

feh="feh --bg-fill"

mpv="mpv --wid feh --no-config --keepaspect=no --loop \
    --no-border --vd-lavc-fast --x11-bypass-compositor=no \
    --gapless-audio=yes --vo=xv --hwdec=auto --really-quiet \
    --name=mpvbg"

$feh $mpv "$1" > /dev/null 2>&1 &

echo -n $! > $HOME/.cache/mpvbg.pid
