#! /bin/sh

# Set-up keybindings
sxhkd &
setxkbmap -layout "us,ru" -option "grp:alt_shift_toggle"

# Set-up compositor manager + panel
(compton &)
$HOME/.config/polybar/launch.sh

# Set-up wal run
wal -R

# Set-up BSPWM properties
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1

gap=12
inner_gap=12
bspc config window_gap          $inner_gap
bspc config top_padding         $gap
bspc config left_padding        $gap
bspc config right_padding       $gap
bspc config bottom_padding      $gap

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
